# install OS
FROM ubuntu:latest

# Author information
MAINTAINER Yoshitaro Takaesu <useakat@gmail.com>

ENV CHEFHOME /chef-repo
ADD chef-repo /chef-repo
ADD .bashrc /root/.bashrc
ADD .bash_profile /root/.bash_profile
ADD .bash_aliases /root/.bash_aliases
ADD run.sh /source.sh

RUN chmod +x /source.sh
RUN apt-get -y update
RUN apt-get -y upgrade
RUN mkdir /root/packages

# install Chef
RUN apt-get -y install curl
RUN curl -L http://www.opscode.com/chef/install.sh | bash
RUN cd ${CHEFHOME} && chef-solo -c ${CHEFHOME}/solo.rb -j ${CHEFHOME}/nodes/docker.json

# install developper tools
RUN apt-get -y install wget
RUN apt-get -y install git
RUN apt-get -y install build-essential
RUN apt-get -y install zlib1g-dev
RUN apt-get -y install cython
RUN apt-get -y install tclsh
RUN apt-get -y install python-pip
RUN pip install numpy

# install ROOT
RUN wget https://root.cern.ch/download/root_v5.34.34.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
RUN tar zxvf root_v5.34.34.Linux-ubuntu14-x86_64-gcc4.8.tar.gz -C /root/packages
RUN echo "# ROOT ENV" >> /root/.bashrc
RUN echo "export ROOTSYS=$PACKAGES/root" >> /root/.bashrc
RUN echo "export PATH=$ROOTSYS/bin:$PATH" >> /root/.bashrc
RUN echo "export LD_LIBRARY_PATH=$ROOTSYS/lib/root:$LD_LIBRARY_PATH" >> /root/.bashrc
RUN rm -rf root_v5.34.34.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
RUN /source.sh

# install CheckMATE
RUN wget http://www.hepforge.org/archive/checkmate/CheckMATE-1.2.2.tar.gz
RUN tar zxvf CheckMATE-1.2.2.tar.gz -C /root/packages
RUN cd /root/packages/CheckMATE-1.2.2;./configure --with-rootsys=/root/packages/root
RUN cd /root/packages/CheckMATE-1.2.2;make
RUN rm -rf /CheckMATE-1.2.2.tar.gz

RUN rm -rf /source.sh

### notes
# # install python 
# RUN wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
# RUN tar zxvf Python-2.7.10.tgz
# RUN Python-2.7.10/configure --enable-shared --with-zlib=/usr/include
# RUN make
# RUN make install
# RUN echo "include /usr/local/bin >> /etc/ld.so.conf"
# RUN ldconfig
# RUN echo "# Python ENV" >> /root/.bashrc
# RUN echo "export LD_LIBRARY_PATH=/usr/local/lib/python2.7/:$LD_LIBRARY_PATH" >> /root/.bashrc
# RUN rm -rf Python-2.7.10 Python-2.7.10.tgz
