---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
- name: debian-8.0
- name: centos-7.1

suites:
- name: default
  run_list:
  - recipe[test]
  - recipe[emacs]
